version: 1.0.{build}
os: Visual Studio 2015 RC
init:
- git config --global core.autocrlf true
build_script:
- cd build
- powershell -Command .\build.ps1 -VisualStudioVersion "14.0" -InstallSHFB -Verbosity minimal -Logger "${env:ProgramFiles}\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cd ..
after_build:
- cd build
- powershell -Command .\appveyor-deploy-docs.ps1
- cd ..
# Only run tests with the attribute [TestCategory("Unit")]. These tests are expected to
# run consistently in an automated build environment, and failure certainly indicates
# a bug or regression in the codebase.
test_script:
- vstest.console /logger:Appveyor /TestCaseFilter:"TestCategory=Unit" "src\testing\integration\bin\Release\OpenStackNet.Testing.Integration.dll"
- vstest.console /logger:Appveyor /TestCaseFilter:"TestCategory=Unit" "src\testing\unit\bin\Release\OpenStackNet.Testing.Unit.dll"
